### PR TITLE
Update PySCIPOpt to 2.0.0 for use with SCIP 6.0.0

### PR DESCRIPTION
**Pull request by kschaef**
Using the combo of PySCIPOp v2.0.0 and SCIP 6.0.0 seems to help resolve blacklocus/canadapricing#84

### CODE REVIEW

**Review by ruhul-blacklocus — APPROVED** [review]

**Review by emmalzhang — APPROVED** [review]
I'm good with this. On a side note, where are we with the licensing for SCIP 6.0.0?

**Comment by chadbay** [comment]
licensing is just a phone call away, Dave and I need to do it.

On Tue, Jul 10, 2018 at 11:44 AM Emma Zhang <notifications@github.com>
wrote:

> *@emmalzhang* approved this pull request.
>
> I'm good with this. On a side note, where are we with the licensing for
> SCIP 6.0.0?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_blacklocus_PySCIPOpt_pull_5-23pullrequestreview-2D135913483&d=DwMCaQ&c=9tmmt9jW9iYtnQErYe7MghIMXo3P4lZgHZz2ojJyVho&r=Er7RqzgToi369ZG13MyOKgOvgvA64nei5Dy4VlvfT3E&m=rgH4QhG5uR8IGBl1FCrAZFPNt6Nd8GQblwZ6GOuBtts&s=RO_DeT9IezLtntiFx2YeYafiQIDRZJiZ_kkLHicqWU4&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADp9TFSMCa-2DrMHF0AWYqXqSKKOz9-2DLjIks5uFNoAgaJpZM4VJubU&d=DwMCaQ&c=9tmmt9jW9iYtnQErYe7MghIMXo3P4lZgHZz2ojJyVho&r=Er7RqzgToi369ZG13MyOKgOvgvA64nei5Dy4VlvfT3E&m=rgH4QhG5uR8IGBl1FCrAZFPNt6Nd8GQblwZ6GOuBtts&s=ypT34zvGqVE3kCxF7_FsSc8fH08JFVFmen7VHwkurWE&e=>
> .
>
-- 
Chad Bayer
Engineering Manager | BlackLocus
Home Depot Innovation Lab
chad@blacklocus.com
101 W. 6th St • Suite 700 • Austin, TX 78701
<https://maps.google.com/?q=101+W.+6th+St+%E2%80%A2+Suite+700+%E2%80%A2+Austin,+TX+78701&entry=gmail&source=g>

**Comment by whwright** [comment]
`4108e90` is the commit hash tagged with 2.0.0 here https://github.com/SCIP-Interfaces/PySCIPOpt/releases/tag/v2.0.0

There are 4 commits in this PR after that. Is that intentional?

**Comment by kschaef** [comment]
I mostly just figured we could pull the latest and then pick out the commit we wanted

**Comment by whwright** [comment]
yah that works

**Review by whwright — APPROVED** [review]

**Pull request merged**
